const PrivacyPage = () => {
    return (
        <>
                <div className="px-[10%] pt-32 pb-24">
                    <h1 className="text-3xl md:text-4xl font-semibold">Privacy Policy</h1>
                    <p>Last updated: October 07, 2025</p>
                    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    <h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>
                    <h3 className="text-xl font-semibold">Interpretation</h3>
                    <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    <h3 className="text-xl font-semibold">Definitions</h3>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul>
                    <li>
                    <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Cireon Dev, operated by Maksym Tovkai.</p>
                    </li>
                    <li>
                    <p><strong>AI Service Provider</strong> means OpenAI, Inc., which provides artificial intelligence services for our chatbot functionality.</p>
                    </li>
                    <li>
                    <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                    </li>
                    <li>
                    <p><strong>Country</strong> refers to:  Austria</p>
                    </li>
                    <li>
                    <p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
                    </li>
                    <li>
                    <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                    </li>
                    <li>
                    <p><strong>Service</strong> refers to the Website.</p>
                    </li>
                    <li>
                    <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                    </li>
                    <li>
                    <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                    </li>
                    <li>
                    <p><strong>Website</strong> refers to Cireon Dev, accessible from <a href="https://www.cireon.dev/" rel="external nofollow noopener" target="_blank">https://www.cireon.dev/</a></p>
                    </li>
                    <li>
                    <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                    </li>
                    </ul>
                    <h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
                    <h3 className="text-xl font-semibold">Types of Data Collected</h3>
                    <h4 className="text-lg font-semibold">Personal Data</h4>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul>
                    <li>
                    <p>Email address (when you contact us or use the contact form)</p>
                    </li>
                    <li>
                    <p>First name and last name (when you provide them voluntarily)</p>
                    </li>
                    <li>
                    <p>Project information and requirements (when you inquire about our services)</p>
                    </li>
                    <li>
                    <p>Chat messages (when you use our AI chatbot)</p>
                    </li>
                    <li>
                    <p>Usage Data</p>
                    </li>
                    </ul>
                    <h4 className="text-lg font-semibold">Usage Data</h4>
                    <p>Usage Data is collected automatically when using the Service.</p>
                    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                    <p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
                    <h4 className="text-lg font-semibold">Tracking Technologies and Cookies</h4>
                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                    <ul>
                    <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                    </ul>
                    <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the <a href="https://www.privacypolicies.com/blog/privacy-policy-template/#Use_Of_Cookies_Log_Files_And_Tracking" target="_blank">Privacy Policies website</a> article.</p>
                    <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
                    <ul>
                    <li>
                    <p><strong>Necessary / Essential Cookies</strong></p>
                    <p>Type: Session Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
                    </li>
                    <li>
                    <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
                    </li>
                    <li>
                    <p><strong>Functionality Cookies</strong></p>
                    <p>Type: Persistent Cookies</p>
                    <p>Administered by: Us</p>
                    <p>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
                    </li>
                    </ul>
                    <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                    
                    <h4 className="text-lg font-semibold">AI Chatbot Data Processing</h4>
                    <p>Our website includes an AI-powered chatbot that uses OpenAI's services to provide responses to your questions. When you interact with our chatbot:</p>
                    <ul>
                    <li>
                    <p>Your chat messages are sent to OpenAI, Inc. for processing to generate responses</p>
                    </li>
                    <li>
                    <p>We do not store your chat messages permanently on our servers</p>
                    </li>
                    <li>
                    <p>OpenAI may temporarily process your messages according to their privacy policy</p>
                    </li>
                    <li>
                    <p>We do not use your chat data for training AI models</p>
                    </li>
                    <li>
                    <p>Chat sessions are not linked to your personal identity unless you voluntarily provide identifying information</p>
                    </li>
                    </ul>
                    <p>By using our chatbot, you consent to the processing of your messages by OpenAI as described above. For more information about OpenAI's data practices, please review their privacy policy at <a href="https://openai.com/privacy" target="_blank" rel="noopener noreferrer">https://openai.com/privacy</a>.</p>
                    
                    <h4 className="text-lg font-semibold">Legal Basis for Processing Personal Data Under GDPR</h4>
                    <p>We may process your Personal Data under the following legal bases:</p>
                    <ul>
                    <li><strong>Consent:</strong> You have given your consent for processing Personal Data for one or more specific purposes (e.g., using our chatbot, receiving marketing communications).</li>
                    <li><strong>Performance of a contract:</strong> Provision of Personal Data is necessary for the performance of an agreement with you and/or for any pre-contractual obligations thereof (e.g., project development services).</li>
                    <li><strong>Legitimate interests:</strong> Processing Personal Data is necessary for the purposes of the legitimate interests pursued by us (e.g., website analytics, security, business operations).</li>
                    <li><strong>Legal obligations:</strong> Processing Personal Data is necessary for compliance with a legal obligation to which we are subject.</li>
                    </ul>
                    
                    <h3 className="text-xl font-semibold">Use of Your Personal Data</h3>
                    <p>The Company may use Personal Data for the following purposes:</p>
                    <ul>
                    <li>
                    <p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service and provide AI chatbot functionality.</p>
                    </li>
                    <li>
                    <p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of contracts for web development, mobile app development, and other services You have requested from Us.</p>
                    </li>
                    <li>
                    <p><strong>To contact You:</strong> To contact You by email regarding project inquiries, quotes, and service-related communications.</p>
                    </li>
                    <li>
                    <p><strong>To manage Your requests:</strong> To attend and manage Your requests for quotes, project consultations, and other business inquiries.</p>
                    </li>
                    <li>
                    <p><strong>To provide project services:</strong> To deliver web development, mobile app development, AI integration, and other technical services as requested.</p>
                    </li>
                    <li>
                    <p><strong>For business operations:</strong> We may use Your information for legitimate business purposes such as project management, client communication, and service improvement.</p>
                    </li>
                    </ul>
                    <p>We may share Your personal information in the following situations:</p>
                    <ul>
                    <li><strong>With AI Service Providers:</strong> We share chat messages with OpenAI, Inc. to provide AI chatbot functionality. OpenAI processes this data according to their privacy policy and data processing agreements.</li>
                    <li><strong>With Service Providers:</strong> We may share Your personal information with third-party service providers who assist us in operating our website, conducting business, or serving our users.</li>
                    <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
                    <li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your explicit consent.</li>
                    </ul>
                    <h3 className="text-xl font-semibold">Retention of Your Personal Data</h3>
                    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                    <p><strong>Specific retention periods:</strong></p>
                    <ul>
                    <li><strong>Contact form submissions:</strong> Retained for 3 years for business purposes and potential follow-up</li>
                    <li><strong>Project-related communications:</strong> Retained for 7 years for legal and tax compliance</li>
                    <li><strong>Chat messages:</strong> Not stored permanently; processed in real-time by OpenAI</li>
                    <li><strong>Usage Data:</strong> Retained for 2 years for analytics and security purposes</li>
                    <li><strong>Cookies:</strong> Session cookies deleted when browser closes; persistent cookies retained for up to 1 year</li>
                    </ul>
                    <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.</p>
                    <h3 className="text-xl font-semibold">Transfer of Your Personal Data</h3>
                    <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
                    <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                    <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                    <h3 className="text-xl font-semibold">Your Data Protection Rights Under GDPR</h3>
                    <p>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
                    <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>
                    <p>In certain circumstances, you have the following data protection rights:</p>
                    <ul>
                    <li><strong>The right to access, update or to delete the information we have on you.</strong> You can contact us to request access to, update, or delete your personal information.</li>
                    <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
                    <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
                    <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
                    <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
                    <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where we relied on your consent to process your personal information.</li>
                    </ul>
                    <p>Please note that we may ask you to verify your identity before responding to such requests.</p>
                    <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>
                    <h3 className="text-xl font-semibold">Disclosure of Your Personal Data</h3>
                    <h4 className="text-lg font-semibold">Business Transactions</h4>
                    <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                    <h4 className="text-lg font-semibold">Law enforcement</h4>
                    <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                    <h4 className="text-lg font-semibold">Other legal requirements</h4>
                    <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                    <ul>
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                    </ul>
                    <h3 className="text-xl font-semibold">Security of Your Personal Data</h3>
                    <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                    <h2 className="text-2xl font-semibold">Children's Privacy</h2>
                    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
                    <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
                    <h2 className="text-2xl font-semibold">Links to Other Websites</h2>
                    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
                    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                    <h2 className="text-2xl font-semibold">Changes to this Privacy Policy</h2>
                    <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                    <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
                    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                    <h2 className="text-2xl font-semibold">Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                    <ul>
                    <li>
                    <p><strong>By email:</strong> me@cireon.dev</p>
                    </li>
                    <li>
                    <p><strong>By Telegram:</strong> @ChaRsKiY_09</p>
                    </li>
                    <li>
                    <p><strong>By visiting this page on our website:</strong> <a href="https://www.cireon.dev/privacy" rel="external nofollow noopener" target="_blank">https://www.cireon.dev/privacy</a></p>
                    </li>
                    <li>
                    <p><strong>Data Protection Officer:</strong> Maksym Tovkai (me@cireon.dev)</p>
                    </li>
                    </ul>
                    <p><strong>Response Time:</strong> We will respond to your privacy-related inquiries within 30 days as required by GDPR.</p>
                </div>
        </>
    )
}

export default PrivacyPage